# Generated by Django 3.1.1 on 2020-11-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfood',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
